---Section 10. Transactions

---Summary: in this tutorial, you will learn how to handle PostgreSQL transactions using the BEGIN, COMMIT, and ROLLBACK statements.

DROP TABLE IF EXISTS accounts;

CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance DEC(15,2) NOT NULL CHECK(balance >= 0),
    PRIMARY KEY(id)
);


INSERT INTO accounts(name,balance)
VALUES('Bob',10000)
returning*;


BEGIN;
INSERT INTO accounts(name,balance)
VALUES('Alice',10000);


SELECT 
    id,
    name,
    balance
FROM 
    accounts;
	
----Commit a transaction


-- start a transaction
BEGIN;

-- insert a new row into the accounts table
INSERT INTO accounts(name,balance)
VALUES('Mujju',20000);

-- commit the change (or roll it back later)
COMMIT;


select * from accounts;


-- start a transaction
BEGIN;

UPDATE accounts
SET balance = balance - 1000
WHERE id =  1;

-- rollback the changes
ROLLBACK;
---If you retrieve data from the accounts table, you’ll won’t see the changes because it was rolled back .


 



























































