----Section 12. Managing Tables
---PostgreSQL Identity Column
* Generated always as identity;
* Generated by default as identity;
* Generated always as identity with sequence;

create table users_idt(
	user_id int generated always as identity primary key,
	username varchar(255),
	email text
);

insert into users_idt(user_id,username,email) 
values (1,'Mujju','Mujju@gmail.com');

insert into users_idt(username,email) 
values ('Mujju','Mujju@gmail.com');

select * from users_idt;


-----Generated by default as identity

create table users_idt1(
	user_id int generated by default as identity primary key,
	username varchar(255),
	email text
);

insert into users_idt1(user_id,username,email) 
values (1,'Mujju','Mujju@gmail.com');

select * from users_idt1;

insert into users_idt1(username,email) 
values ('Keff','Keff@gmail.com');

insert into users_idt1(user_id,username,email) 
values (10,'Mujju','Mujju@gmail.com');


-----------genereated always as identity with sequence
drop table users_idt2;

create table users_idt2(
	user_id int generated always as identity (start with 101 increment by 1) primary key,
	username varchar(255),
	email text
);

insert into users_idt2(user_id,username,email) 
values (1,'Mujju','Mujju@gmail.com');

select * from users_idt2;

insert into users_idt2(username,email) 
values ('Keff','Keff@gmail.com'),('MUJJU','Mujju@gmail.com');

